name: top_gym
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0
  calendar_timeline: ^1.0.5
  flutter_secure_storage: ^7.0.1
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.2.3
  local_auth: ^2.1.3
  firebase_core: ^2.3.0
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.1.2
  google_fonts: ^3.0.1
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  quickalert: ^1.0.0
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  step_progress_indicator: ^1.0.2
  google_sign_in: ^5.4.2
  persistent_bottom_nav_bar: ^5.0.2
  pin_code_fields: ^7.4.0
  country_picker: ^2.0.19
  firebase_storage: ^11.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/